[tox]
skipsdist = true
envlist = py312, py313

[gh-actions]
python =
    3.12: py312
    3.13: py313

[testenv]
runner = uv-venv-lock-runner
dependency_groups = dev
package = editable
commands =
    python -m pytest tests
    pyright
